#include "Countries.hpp"

#include <Poco/Dynamic/Var.h>
#include <Poco/JSON/JSON.h>
#include <Poco/JSON/Parser.h>
#include <algorithm>
#include <string>
#include <unordered_map>

using std::string;

static std::unordered_map<std::string, std::string> countries{
    {"AFG", "Afghanistan"},
    {"ALA", "Aland Islands"},
    {"ALB", "Albania"},
    {"DZA", "Algeria"},
    {"ASM", "American Samoa"},
    {"AND", "Andorra"},
    {"AGO", "Angola"},
    {"AIA", "Anguilla"},
    {"ATA", "Antarctica"},
    {"ATG", "Antigua And Barbuda"},
    {"ARG", "Argentina"},
    {"ARM", "Armenia"},
    {"ABW", "Aruba"},
    {"AUS", "Australia"},
    {"AUT", "Austria"},
    {"AZE", "Azerbaijan"},
    {"BHS", "Bahamas"},
    {"BHR", "Bahrain"},
    {"BGD", "Bangladesh"},
    {"BRB", "Barbados"},
    {"BLR", "Belarus"},
    {"BEL", "Belgium"},
    {"BLZ", "Belize"},
    {"BEN", "Benin"},
    {"BMU", "Bermuda"},
    {"BTN", "Bhutan"},
    {"BOL", "Bolivia"},
    {"BES", "Bonaire Sint Eustatius And Saba"},
    {"BIH", "Bosnia And Herzegovina"},
    {"BWA", "Botswana"},
    {"BVT", "Bouvet Island"},
    {"BRA", "Brazil"},
    {"IOT", "British Indian Ocean Territory"},
    {"BRN", "Brunei"},
    {"BGR", "Bulgaria"},
    {"BFA", "Burkina Faso"},
    {"BDI", "Burundi"},
    {"CPV", "Cabo Verde"},
    {"KHM", "Cambodia"},
    {"CMR", "Cameroon"},
    {"CAN", "Canada"},
    {"CYM", "Cayman Islands"},
    {"CAF", "Central African Republic"},
    {"TCD", "Chad"},
    {"CHL", "Chile"},
    {"CHN", "China"},
    {"CXR", "Christmas Island"},
    {"CCK", "Cocos Islands"},
    {"CCK", "Keeling Islands"},
    {"COL", "Colombia"},
    {"COM", "Comoros"},
    {"COG", "Congo"},
    {"COD", "Democratic Republic Of The Congo"},
    {"COK", "Cook Islands"},
    {"CRI", "Costa Rica"},
    {"CIV", "Ivory Coast"},
    {"HRV", "Croatia"},
    {"CUB", "Cuba"},
    {"CUW", "Curaçao"},
    {"CYP", "Cyprus"},
    {"CZE", "Czech Republic"},
    {"DNK", "Denmark"},
    {"DJI", "Djibouti"},
    {"DMA", "Dominica"},
    {"DOM", "Dominican Republic "},
    {"ECU", "Ecuador"},
    {"EGY", "Egypt"},
    {"SLV", "El Salvador"},
    {"GNQ", "Equatorial Guinea"},
    {"ERI", "Eritrea"},
    {"EST", "Estonia"},
    {"ETH", "Ethiopia"},
    // Sovereignty dispute between Argentina and United Kingdom
    {"FLK", "Falkland Islands"},
    {"FRO", "Faroe Islands"},
    {"FJI", "Fiji"},
    {"FIN", "Finland"},
    {"FRA", "France"},
    {"GUF", "French Guiana"},
    {"PYF", "French Polynesia"},
    {"ATF", "French Southern Territories"},
    {"GAB", "Gabon"},
    {"GMB", "Gambia"},
    {"GEO", "Georgia"},
    {"D", "Germany"},
    {"GHA", "Ghana"},
    {"GIB", "Gibraltar"},
    {"GRC", "Greece"},
    {"GRL", "Greenland"},
    {"GRD", "Grenada"},
    {"GLP", "Guadeloupe"},
    {"GUM", "Guam"},
    {"GTM", "Guatemala"},
    {"GGY", "Guernsey"},
    {"GIN", "Guinea"},
    {"GNB", "Guinea Bissau"},
    {"GUY", "Guyana"},
    {"HTI", "Haiti"},
    {"HMD", "Heard Island And Mcdonald Islands"},
    {"VAT", "Vatican City State"},
    {"HND", "Honduras"},
    {"HKG", "Hong Kong"},
    {"HUN", "Hungary"},
    {"ISL", "Iceland"},
    {"IND", "India"},
    {"IDN", "Indonesia"},
    {"IRN", "Iran"},
    {"IRQ", "Iraq"},
    {"IRL", "Ireland"},
    {"IMN", "Isle Of Man"},
    {"ISR", "Israel"},
    {"ITA", "Italy"},
    {"JAM", "Jamaica"},
    {"JPN", "Japan"},
    {"JEY", "Jersey"},
    {"JOR", "Jordan"},
    {"KAZ", "Kazakhstan"},
    {"KEN", "Kenya"},
    {"KIR", "Kiribati"},
    {"RKS", "Kosovo"},
    {"PRK", "North Korea"},
    {"KOR", "South Korea"},
    {"KWT", "Kuwait"},
    {"KGZ", "Kyrgyzstan"},
    {"LAO", "Lao Democratic Republic"},
    {"LVA", "Latvia"},
    {"LBN", "Lebanon"},
    {"LSO", "Lesotho"},
    {"LBR", "Liberia"},
    {"LBY", "Libya"},
    {"LIE", "Liechtenstein"},
    {"LTU", "Lithuania"},
    {"LUX", "Luxembourg"},
    {"MAC", "Macao"},
    {"MKD", "Macedonia"},
    {"MDG", "Madagascar"},
    {"MWI", "Malawi"},
    {"MYS", "Malaysia"},
    {"MDV", "Maldives"},
    {"MLI", "Mali"},
    {"MLT", "Malta"},
    {"MHL", "Marshall Islands"},
    {"MTQ", "Martinique"},
    {"MRT", "Mauritania"},
    {"MUS", "Mauritius"},
    {"MYT", "Mayotte"},
    {"MEX", "Mexico"},
    {"FSM", "Micronesia"},
    {"MDA", "Moldova"},
    {"MCO", "Monaco"},
    {"MNG", "Mongolia"},
    {"MNE", "Montenegro"},
    {"MSR", "Montserrat"},
    {"MAR", "Morocco"},
    {"MOZ", "Mozambique"},
    {"MMR", "Myanmar"},
    {"NAM", "Namibia"},
    {"NRU", "Nauru"},
    {"NPL", "Nepal"},
    {"NLD", "Netherlands"},
    {"ANT", "Netherlands Antilles"},
    {"NTZ", "Neutral Zone"},
    {"NCL", "New Caledonia"},
    {"NZL", "New Zealand"},
    {"NIC", "Nicaragua"},
    {"NER", "Niger"},
    {"NGA", "Nigeria"},
    {"NIU", "Niue"},
    {"NFK", "Norfolk Island"},
    {"MNP", "Northern Mariana Islands"},
    {"NOR", "Norway"},
    {"OMN", "Oman"},
    {"PAK", "Pakistan"},
    {"PLW", "Palau"},
    {"PSE", "Palestine"},
    {"PAN", "Panama"},
    {"PNG", "Papua New Guinea"},
    {"PRY", "Paraguay"},
    {"PER", "Peru"},
    {"PHL", "Philippines"},
    {"PCN", "Pitcairn"},
    {"POL", "Poland"},
    {"PRT", "Portugal"},
    {"PRI", "Puerto Rico"},
    {"QAT", "Qatar"},
    {"REU", "Reunion"},
    {"ROU", "Romania"},
    {"RUS", "Russia"},
    {"RWA", "Rwanda"},
    {"BLM", "Saint Barthelemy"},
    {"SHN", "Saint Helena Ascension And Tristan Da Cunha"},
    {"KNA", "Saint Kitts And Nevis"},
    {"LCA", "Saint Lucia"},
    {"MAF", "Saint Martin"},
    {"SPM", "Saint Pierre And Miquelon"},
    {"VCT", "Saint Vincent And The Grenadines"},
    {"WSM", "Samoa"},
    {"SMR", "San Marino"},
    {"STP", "Sao Tome And Principe"},
    {"SAU", "Saudi Arabia"},
    {"SEN", "Senegal"},
    {"SRB", "Serbia"},
    {"SYC", "Seychelles"},
    {"SLE", "Sierra Leone"},
    {"SGP", "Singapore"},
    {"SXM", "Sint Maarten"},
    {"SVK", "Slovakia"},
    {"SVN", "Slovenia"},
    {"SLB", "Solomon Islands"},
    {"SOM", "Somalia"},
    {"ZAF", "South Africa"},
    {"SGS", "South Georgia And The South Sandwich Islands"},
    {"SSD", "South Sudan"},
    {"ESP", "Spain"},
    {"LKA", "Sri Lanka"},
    {"SDN", "Sudan"},
    {"SUR", "Suriname"},
    {"SJM", "Svalbard And Jan Mayen"},
    {"SWZ", "Swaziland"},
    {"SWE", "Sweden"},
    {"CHE", "Switzerland"},
    {"SYR", "Syria"},
    {"TWN", "Taiwan"},
    {"TJK", "Tajikistan"},
    {"TZA", "Tanzania"},
    {"THA", "Thailand"},
    {"TLS", "East Timor"},
    {"TGO", "Togo"},
    {"TKL", "Tokelau"},
    {"TON", "Tonga"},
    {"TTO", "Trinidad And Tobago"},
    {"TUN", "Tunisia"},
    {"TUR", "Turkey"},
    {"TKM", "Turkmenistan"},
    {"TCA", "Turks And Caicos Islands"},
    {"TUV", "Tuvalu"},
    {"UGA", "Uganda"},
    {"UKR", "Ukraine"},
    {"ARE", "Arab Emirates"},
    {"GB", "United Kingdom"},
    {"GBR", "British"},
    {"GBD", "British Overseas Territories"},
    {"GBN", "British National Overseas"},
    {"GBO", "British Overseas Citizen"},
    {"GBP", "British Protected"},
    {"GBS", "British Subject"},
    {"USA", "United States"},
    {"UMI", "United States Minor Outlying Islands"},
    {"URY", "Uruguay"},
    // ICAO Example. Not a real country
    {"UTO", "Utopia"},
    {"UZB", "Uzbekistan"},
    {"VUT", "Vanuatu"},
    {"VEN", "Venezuela"},
    {"VNM", "Vietnam"},
    {"VGB", "Virgin Islands"},
    {"VIR", "Virgin Islands Of The United States"},
    {"WLF", "Wallis And Futuna"},
    {"ESH", "Western Sahara"},
    {"YEM", "Yemen"},
    {"ZMB", "Zambia"},
    {"ZWE", "Zimbabwe"},
    {"ZIM", "Republic of Zimbabwe"},
    {"EUE", "European Union"},
    {"UNO", "United Nations Organization"},
    {"UNA", "United Nations Agency"},
    {"UNK", "Kosovo"},
    {"XBA", "African Development Bank"},
    {"XIM", "Afrexim"},
    {"XCC", "Caricom"},
    {"XCO", "Comesa"},
    {"XEC", "Ecowas"},
    {"INP", "Interpol"},
    {"XOM", "Military Order Of Malta"},
    {"XXA", "Refugee"},
    {"XXB", "Refugee B"},
    {"XXX", "Unknown"},
};

bool Countries::has_country(string country) {
  country.erase(std::remove(country.begin(), country.end(), '<'),
                country.end());
  return countries.find(country) != countries.end();
}

void Countries::toJson(std::ostream &out) {
  static string code("code");
  static string en("en");
  Poco::JSON::Array ret;
  size_t idx = 0;
  for (auto const &[key, val] : countries) {
    Poco::JSON::Object item;
    item.set(code, key);
    item.set(en, val);
    ret.set(idx, item);
    idx++;
  }
  ret.stringify(out);
}
